### ISSUE TITLE
highlight shared ideas of religious groups / ideas

### ISSUE THREAD

**Issue by CNoviNov** [acdh-oeaw/youbeon-frontend#29]
Is it possible to show the ideas which selected religious groups have in common in a different colour? (same colour as on place-page for "Gemeinsame Orte")? Right now they appear in the same colour regardless of them being connected to one or more than one of the selected religious groups.
![grafik](https://user-images.githubusercontent.com/94974601/197534355-ab9f0f30-9766-4a74-82b1-a93c33ea45e1.png)

**Comment by CNoviNov** [comment]
add in legend: "Gemeinsame Ideen X" (X being the colour)

**Comment by stefanprobst** [comment]
do we want the same for the "Accounts" screen as well, i.e. highlight "Gemeinsame Accounts" in different color?

**Comment by CNoviNov** [comment]
I think, it would be very intuitve to have them in the same way, so yes.
