### ISSUE TITLE
Input from designer; landing page

### ISSUE THREAD

**Issue by CNoviNov** [acdh-oeaw/youbeon-frontend#45]
- [ ] Menu on top slightly increase in size (see www.youbeon.eu)
- [x] fonts (throughout the landing page) --> YouBeOn fonts (for fonts see youbeon_info.pdf ; )
- [x] landing page: "Hier gehts zur YouBeOnMap"-button colour (#424C55); font colour white
- [ ] three colums Orte/Accounts/Ideen, design like landing page (increase size of "sprechblasen"-icons + font; see 221106-App.Input.pdf)

[youbeon_Info.pdf](https://github.com/acdh-oeaw/youbeon-frontend/files/9969007/youbeon_Info.pdf)
[221106-App Input.pdf](https://github.com/acdh-oeaw/youbeon-frontend/files/9969013/221106-App.Input.pdf)

**Comment by stefanprobst** [comment]
fixed
