### ISSUE TITLE
input from designer; impressum

### ISSUE THREAD

**Issue by CNoviNov** [acdh-oeaw/youbeon-frontend#46]
impressum-bar on the bottom (Orte, Accounts, Ideen-pages): if possible, change colour to #424C55

Impressum page, if possible change font according to YouBeOn-fonts

[youbeon_Info.pdf](https://github.com/acdh-oeaw/youbeon-frontend/files/9969074/youbeon_Info.pdf)

**Comment by stefanprobst** [comment]
please clarify - the imprint page is already using "Noto Sans". do you mean using Chicago for the first heading?

**Comment by CNoviNov** [comment]
ideally it should resemble the appearance of the impressum page on the youbeon.eu webpage. 

the impressum heading including the bubble and in Chicago

the main font for the text is "Noto Sans Light HK"

![grafik](https://user-images.githubusercontent.com/94974601/200792445-3651b2b6-ff0c-4d49-9c15-246decd9c3eb.png)
