### ISSUE TITLE
odd behaviour of networks if term is searched before it has come to a standstill

### ISSUE THREAD

**Issue by CNoviNov** [acdh-oeaw/youbeon-frontend#49]
Right away, this is not a big issue, but rather an oddity (and if it is not fixed, that's not a problem):

After reloading any of the two networks the map is still moving. If I enter a search term at this stage (before the network has come to a standstill), it somehow emits a power to the system which makes it disperse slightly. I think this is particularly the case if you look for a term which is in the centre (so, for example, in ideas "Gott", in accounts "zeit_im_Bild").

As I said, this is not a big issue, but maybe something to look at if there is still some time left. If it can't be fixed easily, it's no problem. I would rather live with the odd behaviour than not having any movement at the beginning.

**Comment by stefanprobst** [comment]
note to self:

this happens because we need to sort highlighted nodes to the end of the nodes list every time node highlights change, in order to guarantee they end up on top in the stacking order. unfortunately, feeding new graph data to the force-graph library will always reheat the simulation.

**Comment by stefanprobst** [comment]
tried fixing this, which required patching the network-graph library we use - please test and re-open in case this is still not fully fixed. thx
