### ISSUE TITLE
Landing page fixating top bar

### ISSUE THREAD

**Issue by CNoviNov** [acdh-oeaw/youbeon-frontend#54]
The top bar of the landing page (YouBeOn-logo, Orte, Accounts, Ideen, FAQs) should stay visible when scrolling down the page (like on the youbeon.eu homepage)

**Comment by stefanprobst** [comment]
fixed in https://github.com/acdh-oeaw/youbeon-frontend/commit/e13ec8548fc7b3784a8c4610f05ad03c6204b6be
