### ISSUE TITLE
Bug: focus on Orte-Layer

### ISSUE THREAD

**Issue by CNoviNov** [acdh-oeaw/youbeon-frontend#59]
After searching for a place, the page always focuses/centres on the searched place, even if I select another place by clicking on the place with the mouse. E.g. if I search for Salzburg and then move the map to the east and click on Burgenland, the map resets it's focus on Salzburg.

**Comment by stefanprobst** [comment]
fixed in https://github.com/acdh-oeaw/youbeon-frontend/commit/9aaa8aa5470f7fc900098278f3417fa50587fac6
